export const roadmap = [
  {
    id: 1,
    year: 2021,
    month: 9,
    title: "2021 \\ Q4",
    list: [
      { item: "Cosmic pioneers headhunting" },
      { item: "Foundations for the ecosystem" },
    ],
  },
  {
    id: 2,
    year: 2022,
    month: 0,
    title: "2022 \\ Q1",
    list: [
      { item: "Team build" },
      { item: "Social media setup" },
      { item: "Website v1" },
      { item: "Whitepaper" },
      { item: "Cosmic Deck" },
      { item: "Partnerships" },
      { item: "2D artwork" },
      { item: "3D assets" },
      { item: "Teaser" },
      { item: "Moralis integrations" },
    ],
  },
  {
    id: 3,
    year: 2022,
    month: 3,
    title: "2022 \\ Q2",
    list: [
      { item: "Private sale" },
      { item: "dApp Test-net" },
      { item: "Alpha game build" },
      { item: "Marketing push" },
      { item: "IGO’s" },
      { item: "AMA’s" },
      { item: "Auditing" },
      { item: "Initial liquidity" },
      { item: "Cosmic Yields" },
    ],
  },
  {
    id: 4,
    year: 2022,
    month: 6,
    title: "2022 \\ Q3",
    list: [
      { item: "Community push" },
      { item: "Cosmic quests" },
      { item: "Cosmic Shop" },
      { item: "F2P dungeons" },
      { item: "P2E farms" },
      { item: "Cosmic DAO guild" },
      { item: "Marketplace" },
      { item: "AMA’s" },
    ],
  },
  {
    id: 5,
    year: 2022,
    month: 9,
    title: "2022 \\ Q4",
    list: [
      { item: "P2E dungeons" },
      { item: "Professions" },
      { item: "Equipment" },
      { item: "Events" },
      { item: "Merch" },
      { item: "AMA’s" },
    ],
  },
  {
    id: 6,

    title: "2023 \\ Q1",
    year: 2023,
    month: 0,
    list: [
      { item: "Season 1 prep (PVP)" },
      { item: "Achievements" },
      { item: "Epic dungeons" },
      { item: "2nd Audit" },
      { item: "Season 1 begins" },
      { item: "Streaming team" },
      { item: "AMA’s" },
    ],
  },
  {
    id: 7,
    year: 2023,
    month: 3,
    title: "2023 \\ Q2",
    list: [
      { item: "Social rewards (user #code)" },
      { item: "Delegate NFTs" },
      { item: "Guild programs prep" },
      { item: "AMA’s" },
    ],
  },
  {
    id: 8,
    year: 2023,
    month: 6,
    title: "2023 \\ Q3",
    list: [
      { item: "Mobile gaming" },
      { item: "Cross chain prep" },
      { item: "AMA’s" },
    ],
  },
  {
    id: 9,
    year: 2023,
    month: 9,
    title: "2023 \\ Q4",
    list: [{ item: "Learn and Earn" }, { item: "Season 2 preparation" }],
  },
];
