export const teamMembers = [
  {
    id: 1,
    name: "TOM",
    photo: "",
    department: "Cosmic Pioneer",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 2,
    name: "RENATO",
    photo: "",
    department: "Cosmic Dev",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 3,
    name: "OSCAR",
    photo: "",
    department: "Cosmic Dev",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 4,
    name: "TRABS",
    photo: "",
    department: "Cosmic Dev",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 5,
    name: "KROLING",
    photo: "",
    department: "Cosmic Dev",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 6,
    name: "FELIPE",
    photo: "",
    department: "Cosmic Game Dev",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 7,
    name: "SÉRGIO",
    photo: "",
    department: "Cosmic Designer",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 8,
    name: "CHICO",
    photo: "",
    department: "Cosmic Designer",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 9,
    name: "DUKKHART",
    photo: "",
    department: "Cosmic Composer",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 10,
    name: "LEURR",
    photo: "",
    department: "Cosmic Sampler",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
];
export const teamMembers2 = [
  {
    id2: 11,
    name2: "JOW",
    photo2: "",
    department2: "Cosmic 3D Artist",
    info2:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin2: "",
    behance2: "",
    www2: "",
  },
  {
    id2: 12,
    name2: "KENNEDY",
    photo2: "",
    department2: "Cosmic 3D Artist",
    info2:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin2: "",
    behance2: "",
    www2: "",
  },
  {
    id2: 12,
    name2: "YSAKI",
    photo2: "",
    department2: "Cosmic Illustrator",
    info2:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin2: "",
    behance2: "",
    www2: "",
  },
  {
    id2: 13,
    name2: "ELLIE",
    photo2: "",
    department2: "Cosmic Illustrator",
    info2:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin2: "",
    behance2: "",
    www2: "",
  },
  {
    id2: 14,
    name2: "DEBBYR",
    photo2: "",
    department2: "Cosmic Support",
    info2:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin2: "",
    behance2: "",
    www2: "",
  },
  {
    id2: 15,
    name2: "NEVETS",
    photo2: "",
    department2: "Cosmic Advisor",
    info2:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin2: "",
    behance2: "",
    www2: "",
  },
  {
    id2: 16,
    name2: "JOSH",
    photo2: "",
    department2: "Cosmic Advisor",
    info2:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin2: "",
    behance2: "",
    www2: "",
  },
  {
    id2: 17,
    name2: "JOSE",
    photo2: "",
    department2: "Cosmic Advisor",
    info2:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin2: "",
    behance2: "",
    www2: "",
  },
  {
    id2: 18,
    name2: "MOOTZ",
    photo2: "",
    department2: "Cosmic Advisor",
    info2:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin2: "",
    behance2: "",
    www2: "",
  },
];
